### ISSUE TITLE
Error "start must be <= end"

### ISSUE THREAD

**Issue by Raphaww** [tonifisler/generator-styleguide#33]
I ran this generator using:
```bash
$ gulp
$ gulp serve
```

but I was receiving an error while requesting the localurl:

```bash
fs.js: 1475 throw new Error('start must be <= end');
```
I tried using gulp-webserver instead of browser-sync but it throw the same error
I was just trying to use it "as it is" but I couldn't

Then I realized that the assets/js/main.js was an empty js file, just by removing it or adding a simple `console.log` to it, the error stopped to happen

I thing it would be great if you fix this in order to prevent other user to move from this grear generator

**Comment by tonifisler** [comment]
:+1: I'll look into it, thanks!
